name: inventory_app
description: A minimal Flutter inventory app scaffold
version: 0.0.1
publish_to: none
environment:
  sdk: ">=3.3.0 <4.0.0"
dependencies:
  flutter:
    sdk: flutter
  sqflite_common_ffi: ^2.3.2
  path: ^1.9.0
  sqflite: ^2.3.3+1
  shared_preferences: ^2.2.2
  crypto: ^3.0.3
  fl_chart: ^0.66.2
  syncfusion_flutter_pdf: ^24.1.48
  syncfusion_flutter_xlsio: ^24.1.48
  path_provider: ^2.1.1
  open_file: ^3.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

dependency_overrides:
  web: ^0.5.1
